### ISSUE TITLE
Ошибка обновления устройств

### ISSUE THREAD

**Issue by Hamper** [alryaz/hass-component-yandex-smart-home#1]
При попытке обновления списка устройств из яндекса такая ошибка. В исходной интеграции  https://github.com/dmitry-k/yandex_smart_home этой ошибки нет.

```
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/core/smart_home.py", line 46, in _process
    result = await handler(hass, data, message)
  File "/config/custom_components/yandex_smart_home/core/smart_home.py", line 94, in async_devices_sync
    serialized = await entity.devices_serialize()
  File "/config/custom_components/yandex_smart_home/core/helpers.py", line 172, in devices_serialize
    description = cpb.description()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 110, in description
    parameters = self.parameters()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 130, in parameters
    return self.parameters_default()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 651, in parameters_default
    for v in custom_numeric_modes.keys()
AttributeError: 'NoneType' object has no attribute 'keys'
2020-06-30 09:35:51 ERROR (MainThread) [custom_components.yandex_smart_home.core.smart_home] Error handling message {}: {'error_code': 'INTERNAL_ERROR'}
```

**Comment by alryaz** [comment]
@Hamper загрузил апдейт, возможно исправит данную ситуацию. Прошу протестировать, если возможно; если невозможно, опишите, пожалуйста Ваш конфиг в двух словах.

**Comment by Hamper** [comment]
Теперь в логи ничего не пишет, но в яндексе при попытке обновления списка устройств все равно ошибка (при этом устройства, добавленные раньше работают). В конфиге у меня много всего: датчики xiaomi, пылесос, выключатели livolo, rest json датчики, zigbee2mqtt выключатель, телевизоры. Возможно попробую потестировать с отключением части устройств.

**Comment by Hamper** [comment]
Вот как минимум пылесос xiaomi вызывает эту ошибку.

**Comment by Hamper** [comment]
Да, работает все, кроме пылесоса, как только его раскомментирую в конфиге, то сразу эта ошибка.

**Comment by alryaz** [comment]
@Hamper попробуйте последний master именно; вчера занимался плотным дебагом, сейчас не должно происходить более. Если заработает, помечу как релизную версию.

**Comment by Hamper** [comment]
Да, в master определяется пылесос, а так же определилась yeelight люстра, которая раньше не определялась.
