### ISSUE TITLE
Произошла ошибка, попробуйте позже.

### ISSUE THREAD

**Issue by Silent4831** [alryaz/hass-component-yandex-smart-home#2]
Произошла ошибка, попробуйте позже. Если ошибка продолжает возникать, поищите решение проблемы на странице помощи.
Такое сообщение выдает при попытке обновить список устройств. Подскажите как ее решить.
![2020-07-25_00-10-23](https://user-images.githubusercontent.com/37260995/88435718-7a4c3c00-ce0b-11ea-96eb-597d36b701c0.png)

**Comment by nquest** [comment]
Отдаю в яндекс только домен 'light', в нем разные девайсы (только on/off, только с яркостью, с цветом)
при обновлении получаю в логе 
2020-07-25 13:50:46 ERROR (MainThread) [custom_components.yandex_smart_home.core.smart_home] Unexpected error
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/core/smart_home.py", line 46, in _process
    result = await handler(hass, data, message)
  File "/config/custom_components/yandex_smart_home/core/smart_home.py", line 94, in async_devices_sync
    serialized = await entity.devices_serialize()
  File "/config/custom_components/yandex_smart_home/core/helpers.py", line 172, in devices_serialize
    description = cpb.description()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 110, in description
    parameters = self.parameters()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 130, in parameters
    return self.parameters_default()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 651, in parameters_default
    for v in custom_numeric_modes.keys()
AttributeError: 'NoneType' object has no attribute 'keys'
2020-07-25 13:50:46 ERROR (MainThread) [custom_components.yandex_smart_home.core.smart_home] Error handling message {}: {'error_code': 'INTERNAL_ERROR'}


UPD: из ветки master работает.

**Comment by back2net** [comment]
> Произошла ошибка, попробуйте позже. Если ошибка продолжает возникать, поищите решение проблемы на странице помощи.
> Такое сообщение выдает при попытке обновить список устройств. Подскажите как ее решить.
> ![2020-07-25_00-10-23](https://user-images.githubusercontent.com/37260995/88435718-7a4c3c00-ce0b-11ea-96eb-597d36b701c0.png)

Такая же фигня. При чём, сразу после настройки оно работало, но спустя час, надо было обновить устройства и при попытке обновления - вылезло это.

В лог вываливает следующее:
Уровень: ERROR
Logger: custom_components.yandex_smart_home.core.smart_home
Source: custom_components/yandex_smart_home/core/smart_home.py:28
Integration: Yandex Smart Home (documentation, issues)
First occurred: 14:30:30 (1 occurrences)
Last logged: 14:30:30

Error handling message {}: {'error_code': 'INTERNAL_ERROR'}
Уровень: ERROR
Logger: custom_components.yandex_smart_home.core.smart_home
Source: custom_components/yandex_smart_home/functions/capability.py:651
Integration: Yandex Smart Home (documentation, issues)
First occurred: 14:30:30 (1 occurrences)
Last logged: 14:30:30

Unexpected error
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/core/smart_home.py", line 46, in _process
    result = await handler(hass, data, message)
  File "/config/custom_components/yandex_smart_home/core/smart_home.py", line 94, in async_devices_sync
    serialized = await entity.devices_serialize()
  File "/config/custom_components/yandex_smart_home/core/helpers.py", line 172, in devices_serialize
    description = cpb.description()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 110, in description
    parameters = self.parameters()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 130, in parameters
    return self.parameters_default()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 651, in parameters_default
    for v in custom_numeric_modes.keys()
AttributeError: 'NoneType' object has no attribute 'keys'



Upd.
В мастер ветке проблемы нет.

**Comment by zyuv** [comment]
Пытался настроить и тоже такая же ошибка (((

Что такое мастер ветка? @dmitry-k ?

**Comment by back2net** [comment]
> Пытался настроить и тоже такая же ошибка (((
> 
> Что такое мастер ветка? @dmitry-k ?

Нет, в hacs, нажимаешь "три точки" в карточке Yandex Smart Home, там пункт reinstall и выбираешь версию master.

**Comment by zyuv** [comment]
аааа, ясно, сейчас попробую.  Я просто еще только начинаю разбираться )
