### ISSUE TITLE
HA 0.115.2 - Не проходит привязка к Яндексу «invalid HTTP method»

### ISSUE THREAD

**Issue by 2andr** [alryaz/hass-component-yandex-smart-home#4]
Переустановил с нуля Raspbian и  HA 0,115 в Докере.
Настроил SSL доступ
Установил  "Yandex Smart Home" но...
При привязке HA к Яндексу, после ввода Логина и пароля в HA - вылетает ошибка:
![2020-09-20_08-55-47](https://user-images.githubusercontent.com/6235964/93719504-ad047d80-fb8b-11ea-9223-eaa02a0c885b.png)

В логе HA при попытке связать аккаунты возникает запись:
`Logger: aiohttp.server
Source: /usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py:355
First occurred: 10:00:10 (9 occurrences)
Last logged: 10:00:16

Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 275, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method`

ssl настроен и работает....
![2020-09-20_10-03-21](https://user-images.githubusercontent.com/6235964/93719528-ca394c00-fb8b-11ea-9ef7-835991154087.png)

**Comment by 2andr** [comment]
Похоже это всётаки локальные проблемы.
Так как у меня есть статический IP и свой домен - настроил через них
